### ISSUE TITLE
Multiple entries in mysql for the same event.

### ISSUE THREAD

**Issue by aWitch-Doctor** [Karanum/AdamantineShield#21]
I am getting multiple entries for the same event in mysql. I have seen up to 7 entries for the same thing. I have checked and they are all for the same single event. It also takes 60 seconds or more to get results sometimes. I have checked the MC server and it is running fine, no lag. The mysql server is on the same box as the mc server and I only get this issue with AdamantineShield. I am running Sponge Vanilla api 7 build 356 and AdamantineShield 0.3.3-api7. The screen shots are some results of the command in the chat line.

https://puu.sh/yDR6V/58a7d3216f.png
https://puu.sh/yDR83/6017ca99e7.png

**Comment by TomTheHero** [comment]
The same happends with the latest api5 version

**Comment by Karanum** [comment]
This issue is most likely caused by a race condition in writing new worlds/causes/IDs to the database. You can fix it by going into your database and removing all duplicate entries from the AS_World, AS_Id and AS_Cause tables. Once the new version is out, updating will automatically remove these duplicates.
